package com.example.compose
import androidx.compose.ui.graphics.Color


val primaryLight = Color(0xFF28638A)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFF87C6FF)
val onPrimaryContainerLight = Color(0xFF001E30)
val secondaryLight = Color(0xFF28638A)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFB6DBFD)
val onSecondaryContainerLight = Color(0xFF001E30)
val tertiaryLight = Color(0xFF276389)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFCAE6FF)
val onTertiaryContainerLight = Color(0xFF001E30)
val errorLight = Color(0xFF8F4A50)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDADB)
val onErrorContainerLight = Color(0xFF3B0811)
val backgroundLight = Color(0xFFF7F9FF)
val onBackgroundLight = Color(0xFF181C20)
val surfaceLight = Color(0xFFECF3FF)
val onSurfaceLight = Color(0xFF181C20)
val surfaceVariantLight = Color(0xFFC8E2FF)
val onSurfaceVariantLight = Color(0xFF292929)
val outlineLight = Color(0xFF72787E)
val outlineVariantLight = Color(0xFFC1C7CE)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF2D3135)
val inverseOnSurfaceLight = Color(0xFFEEF1F6)
val inversePrimaryLight = Color(0xFF96CCF8)

val primaryLightMediumContrast = Color(0xFF00476A)
val onPrimaryLightMediumContrast = Color(0xFFFFFFFF)
val primaryContainerLightMediumContrast = Color(0xFF427AA1)
val onPrimaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val secondaryLightMediumContrast = Color(0xFF00476A)
val onSecondaryLightMediumContrast = Color(0xFFFFFFFF)
val secondaryContainerLightMediumContrast = Color(0xFF427AA1)
val onSecondaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val tertiaryLightMediumContrast = Color(0xFF00476A)
val onTertiaryLightMediumContrast = Color(0xFFFFFFFF)
val tertiaryContainerLightMediumContrast = Color(0xFF417AA1)
val onTertiaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val errorLightMediumContrast = Color(0xFF6D2F36)
val onErrorLightMediumContrast = Color(0xFFFFFFFF)
val errorContainerLightMediumContrast = Color(0xFFA95F65)
val onErrorContainerLightMediumContrast = Color(0xFFFFFFFF)
val backgroundLightMediumContrast = Color(0xFFF7F9FF)
val onBackgroundLightMediumContrast = Color(0xFF181C20)
val surfaceLightMediumContrast = Color(0xFFF7F9FF)
val onSurfaceLightMediumContrast = Color(0xFF181C20)
val surfaceVariantLightMediumContrast = Color(0xFFDDE3EA)
val onSurfaceVariantLightMediumContrast = Color(0xFF3D4349)
val outlineLightMediumContrast = Color(0xFF5A6066)
val outlineVariantLightMediumContrast = Color(0xFF757B82)
val scrimLightMediumContrast = Color(0xFF000000)
val inverseSurfaceLightMediumContrast = Color(0xFF2D3135)
val inverseOnSurfaceLightMediumContrast = Color(0xFFEEF1F6)
val inversePrimaryLightMediumContrast = Color(0xFF96CCF8)

val primaryLightHighContrast = Color(0xFF00253A)
val onPrimaryLightHighContrast = Color(0xFFFFFFFF)
val primaryContainerLightHighContrast = Color(0xFF00476A)
val onPrimaryContainerLightHighContrast = Color(0xFFFFFFFF)
val secondaryLightHighContrast = Color(0xFF00253A)
val onSecondaryLightHighContrast = Color(0xFFFFFFFF)
val secondaryContainerLightHighContrast = Color(0xFF00476A)
val onSecondaryContainerLightHighContrast = Color(0xFFFFFFFF)
val tertiaryLightHighContrast = Color(0xFF002539)
val onTertiaryLightHighContrast = Color(0xFFFFFFFF)
val tertiaryContainerLightHighContrast = Color(0xFF00476A)
val onTertiaryContainerLightHighContrast = Color(0xFFFFFFFF)
val errorLightHighContrast = Color(0xFF440F17)
val onErrorLightHighContrast = Color(0xFFFFFFFF)
val errorContainerLightHighContrast = Color(0xFF6D2F36)
val onErrorContainerLightHighContrast = Color(0xFFFFFFFF)
val backgroundLightHighContrast = Color(0xFFF7F9FF)
val onBackgroundLightHighContrast = Color(0xFF181C20)
val surfaceLightHighContrast = Color(0xFFF7F9FF)
val onSurfaceLightHighContrast = Color(0xFF000000)
val surfaceVariantLightHighContrast = Color(0xFFDDE3EA)
val onSurfaceVariantLightHighContrast = Color(0xFF1F252A)
val outlineLightHighContrast = Color(0xFF3D4349)
val outlineVariantLightHighContrast = Color(0xFF3D4349)
val scrimLightHighContrast = Color(0xFF000000)
val inverseSurfaceLightHighContrast = Color(0xFF2D3135)
val inverseOnSurfaceLightHighContrast = Color(0xFFFFFFFF)
val inversePrimaryLightHighContrast = Color(0xFFDDEEFF)


val primaryDark = Color(0xFFECB5EC)
val onPrimaryDark = Color(0xFF49204E)
val primaryContainerDark = Color(0xFF623766)
val onPrimaryContainerDark = Color(0xFFFFD6FD)
val secondaryDark = Color(0xFFF6B2E0)
val onSecondaryDark = Color(0xFF4F1E43)
val secondaryContainerDark = Color(0xFF69355B)
val onSecondaryContainerDark = Color(0xFFFFD7EF)
val tertiaryDark = Color(0xFF96CCF8)
val onTertiaryDark = Color(0xFF00344F)
val tertiaryContainerDark = Color(0xFF004B70)
val onTertiaryContainerDark = Color(0xFFCAE6FF)
val errorDark = Color(0xFFFFB2BC)
val onErrorDark = Color(0xFF561D28)
val errorContainerDark = Color(0xFF72333E)
val onErrorContainerDark = Color(0xFFFFD9DD)
val backgroundDark = Color(0xFF171216)
val onBackgroundDark = Color(0xFFEBDFE6)
val surfaceDark = Color(0xFF171216)
val onSurfaceDark = Color(0xFFEBDFE6)
val surfaceVariantDark = Color(0xFF4D444C)
val onSurfaceVariantDark = Color(0xFFD0C3CC)
val outlineDark = Color(0xFF998D96)
val outlineVariantDark = Color(0xFF4D444C)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFEBDFE6)
val inverseOnSurfaceDark = Color(0xFF352F34)
val inversePrimaryDark = Color(0xFF7C4E7F)

val primaryDarkMediumContrast = Color(0xFFF0B9F1)
val onPrimaryDarkMediumContrast = Color(0xFF2B0431)
val primaryContainerDarkMediumContrast = Color(0xFFB280B4)
val onPrimaryContainerDarkMediumContrast = Color(0xFF000000)
val secondaryDarkMediumContrast = Color(0xFFFBB6E4)
val onSecondaryDarkMediumContrast = Color(0xFF2F0328)
val secondaryContainerDarkMediumContrast = Color(0xFFBB7DA8)
val onSecondaryContainerDarkMediumContrast = Color(0xFF000000)
val tertiaryDarkMediumContrast = Color(0xFF9AD1FC)
val onTertiaryDarkMediumContrast = Color(0xFF001828)
val tertiaryContainerDarkMediumContrast = Color(0xFF6096BF)
val onTertiaryContainerDarkMediumContrast = Color(0xFF000000)
val errorDarkMediumContrast = Color(0xFFFFB8C1)
val onErrorDarkMediumContrast = Color(0xFF33030F)
val errorContainerDarkMediumContrast = Color(0xFFC97A85)
val onErrorContainerDarkMediumContrast = Color(0xFF000000)
val backgroundDarkMediumContrast = Color(0xFF171216)
val onBackgroundDarkMediumContrast = Color(0xFFEBDFE6)
val surfaceDarkMediumContrast = Color(0xFF171216)
val onSurfaceDarkMediumContrast = Color(0xFFFFF9FA)
val surfaceVariantDarkMediumContrast = Color(0xFF4D444C)
val onSurfaceVariantDarkMediumContrast = Color(0xFFD4C7D0)
val outlineDarkMediumContrast = Color(0xFFAB9FA8)
val outlineVariantDarkMediumContrast = Color(0xFF8B8089)
val scrimDarkMediumContrast = Color(0xFF000000)
val inverseSurfaceDarkMediumContrast = Color(0xFFEBDFE6)
val inverseOnSurfaceDarkMediumContrast = Color(0xFF2E282D)
val inversePrimaryDarkMediumContrast = Color(0xFF633867)

val primaryDarkHighContrast = Color(0xFFFFF9FA)
val onPrimaryDarkHighContrast = Color(0xFF000000)
val primaryContainerDarkHighContrast = Color(0xFFF0B9F1)
val onPrimaryContainerDarkHighContrast = Color(0xFF000000)
val secondaryDarkHighContrast = Color(0xFFFFF9F9)
val onSecondaryDarkHighContrast = Color(0xFF000000)
val secondaryContainerDarkHighContrast = Color(0xFFFBB6E4)
val onSecondaryContainerDarkHighContrast = Color(0xFF000000)
val tertiaryDarkHighContrast = Color(0xFFF9FBFF)
val onTertiaryDarkHighContrast = Color(0xFF000000)
val tertiaryContainerDarkHighContrast = Color(0xFF9AD1FC)
val onTertiaryContainerDarkHighContrast = Color(0xFF000000)
val errorDarkHighContrast = Color(0xFFFFF9F9)
val onErrorDarkHighContrast = Color(0xFF000000)
val errorContainerDarkHighContrast = Color(0xFFFFB8C1)
val onErrorContainerDarkHighContrast = Color(0xFF000000)
val backgroundDarkHighContrast = Color(0xFF171216)
val onBackgroundDarkHighContrast = Color(0xFFEBDFE6)
val surfaceDarkHighContrast = Color(0xFF171216)
val onSurfaceDarkHighContrast = Color(0xFFFFFFFF)
val surfaceVariantDarkHighContrast = Color(0xFF4D444C)
val onSurfaceVariantDarkHighContrast = Color(0xFFFFF9FA)
val outlineDarkHighContrast = Color(0xFFD4C7D0)
val outlineVariantDarkHighContrast = Color(0xFFD4C7D0)
val scrimDarkHighContrast = Color(0xFF000000)
val inverseSurfaceDarkHighContrast = Color(0xFFEBDFE6)
val inverseOnSurfaceDarkHighContrast = Color(0xFF000000)
val inversePrimaryDarkHighContrast = Color(0xFF421947)


val gradientsColors = listOf(Color(0xFF00B0FF), Color(0xFFE344FC))







